Public Class Settings
    Public Property Var_01_ServerIP As String
    Public Property Var_02_ServerPort As String
    Public Property Var_03_MySql_YGSP As String
    Public Property Var_04_MySql_QA As String
    Public Property Var_05_Factory As String
    Public Property Var_07_Station As String
    Public Property Var_08_Product As String
    Public Property Var_08_StepsName As String
    Public Property Var_08_StepsPrevous As String
    Public Property Var_08_StepsCurrent As String
    Public Property Var_08_AllSteps
    Public Property Var_06_DocsStore As String
    Public Property Var_51_ProStepView_ImagePath As String
    Public Property Var_52_SinglePntInst_ImagePath As String
    Public Property Var_60_020_Position_Initial As String
    Public Property Var_60_020_Position_Tick As String
    Public Property Var_60_020_Position_DateManufacture As String
    Public Property Var_60_030_Position_SerialBefore As String
    Public Property Var_60_120_Position_Initial As String
    Public Property Var_60_120_Position_Tick As String
    Public Property Var_60_120_Position_Circle As String
    Public Property Var_60_130_Position_Circle As String
    Public Property Var_60_130_Position_Tick As String
    Public Property Var_60_140_Position_Circle As String
    Public Property Var_60_140_Position_Tick As String
    Public Property Var_60_140_Position_Initial As String
    Public Property Var_60_150_Position_Circle As String
    Public Property Var_60_150_Position_Tick As String
    Public Property Var_60_150_Position_Initial As String
    Public Property Var_60_160_Position_Circle As String
    Public Property Var_60_160_Position_Tick As String
    Public Property Var_60_170_Position_Circle As String
    Public Property Var_60_170_Position_Initial As String
    Public Property Var_60_170_Position_Tick As String
    Public Property Var_60_180_Position_Circle As String
    Public Property Var_60_180_Position_Initial As String
    Public Property Var_60_180_Position_Tick As String
    Public Property Var_60_180_Position_QicCircle As String
    Public Property Var_60_180_Position_QicInitial As String
    Public Property Var_60_180_Position_QicTick As String
    Public Property Var_60_190_Position_Circle As String
    Public Property Var_60_190_Position_Initial As String
    Public Property Var_60_190_Position_Tick As String
    Public Property Var_60_1900_Position_Circle As String
    Public Property Var_60_1900_Position_Initial As String
    Public Property Var_60_1900_Position_Tick As String
    Public Property Var_60_2000_Position_Circle As String
    Public Property Var_60_2000_Position_Initial As String
    Public Property Var_60_2000_Position_Tick As String
    Public Property Var_60_2000_Position_IM As String
    Public Property Var_60_2000_Position_EUDoC As String
    Public Property Var_60_2000_Position_NoIM As String
    Public Property Var_60_2000_Position_NoEUDoC As String
    Public Property Var_60_2000_Position_Markings As String
End Class
